### ISSUE TITLE
Pre-release documentation sweep

### ISSUE THREAD

**Issue by kdmurray91** [kdmurray91/kWIP#15]
Check and update all documentation for 0.2.0, also check the example workflows to check they work.

- [x] install docs
- [x] rice demo
- [x] CLI

**Comment by warthmann** [comment]
Is the "install" part up to date?

Norman

Sent from a phone

On 12.01.2016, at 15:16, Kevin Murray <notifications@github.com<mailto:notifications@github.com>> wrote:


Check and update all documentation for 0.2.0, also check the example workflows to check they work.

-

**Comment by kdmurray91** [comment]
Yeah, should be, but I'll check in a fresh docker image.

**Comment by kdmurray91** [comment]
Install docs up to date, and moved to one place so that it doesn't get out of sync between readme and docs.

**Comment by kdmurray91** [comment]
https://kwip.readthedocs.org/en/latest/pipelines.html#oryza-sativa-grouping is a little out of date still

**Comment by kdmurray91** [comment]
I think everything is up to date. If @warthmann can take a look and check for any obvious issues when you have time that would be great.
