### ISSUE TITLE
quality check on input files

### ISSUE THREAD

**Issue by warthmann** [kdmurray91/kWIP#19]
it would be nice to have a QC script to inform the user which samples are somewhat questionable:
kwip-stats provides a bunch of numbers that are helpful in assessing whether or not a file/run is suitable for including in the dataset. I.e. 
1) number of reads is outside a reasonable envelope defined by the rest of the samples (the QC script could suggest subsampling for some and dropping of others
2) ratio of kmers vs reads is outside a reasonable envelope. outliers could be flagged. Caution, though, odd samples with different ploidy might look similar.

**Comment by kdmurray91** [comment]
I intend to write this as a separate python script or similar that parses the `kwip-stats` output.
