### ISSUE TITLE
alternative kmer counter

### ISSUE THREAD

**Issue by gorliver** [kdmurray91/kWIP#22]
Is there any chance to use other tools for kmer counting? For example, the KMC3 is pretty fast. If so, it will significantly reduce the running time for large data.

**Comment by kdmurray91** [comment]
Hi @gorliver 

Sorry, it seems I never noticed the creation of this issue. Alas no, the methods we use are quite specific to khmer, or at least to the way khmer does kmer counting. We are working on a second version of kWIP that should be much faster, but this is not quite ready for production use.

Cheers,
Kevin
