### ISSUE TITLE
apt-get: command not found (installation problem)

### ISSUE THREAD

**Issue by UltraSpecialException** [kdmurray91/kWIP#23]
I am following the instructions from http://kwip.readthedocs.io/en/latest/installation.html to install kWIP. However, after executing sudo apt-get install zlib1g-dev cmake build-essential git
and entering in my password, I get:
"sudo: apt-get: command not found"

I am not sure what's wrong here. Any help is appreciated. My computer is a mac if that is relevant.

**Comment by kdmurray91** [comment]
OK, those instructions are for Linux. kWIP is only supported on Linux, but should work OK on a Mac, provided your dataset is quite small (or your Mac very large!). In your case, I would use the [brew package manager](https://brew.sh). I think you'll need to install the dependencies using `brew install zlib cmake git gcc`, though I don't use a Mac so I can't confirm this.

Let me know if you have trouble.
Cheers,
K
