### ISSUE TITLE
Error running kWIP

### ISSUE THREAD

**Issue by Liguorir** [kdmurray91/kWIP#25]
Hello everyone

I would like to ask some help or some explanations.

I was able to run all the kWIP pipeline with the rice example without any problem.

Unfortunately i'm experiencing an error while analyzing my data (metagenome data), during hashing the reads. The program can always end the execution and create the hashes.ct.gz files but this message showed up:

** ERROR: the graph structure is too small for this data set.  Increase data structure size
** with --max_memory_usage/-M.
** Do not use these results!!
** (estimated false positive rate of 0.662; max recommended 0.200)

I tried multiple times to set the "-M" parameter, but other kind of errors normally showed up.

So my questions are:
is anyone of you experiencing the same error ?
were you able to manage it ? 
is my hashes output compromised ?
because my results looks really promising running all the pipeline to the end, but i'm worried that my results could not be realistic due to that error.

Thank you in advance

**Comment by kdm9** [comment]
Hello,

That generally means you have a very large or complex dataset, or are using very small hash sizes. I'd try something like:

```
load-into-counting.py       \
        -N 1                \
        -x 1e10             \
        -k 20               \
        -b                  \
        -f                  \
        -s tsv              \
        $OUTPUT_CTGZ $INPUT_FQ
```

I.e. increase the hash size to 10G. Obviously this will use a lot more RAM, so perhaps see how it goes with `-x 5e9`.

In short, the general trends you observe shouldn't change *heaps*, but it's definitely worth increasing the hash size as much as practical.

Cheers,
K
