### ISSUE TITLE
img.R script does not work

### ISSUE THREAD

**Issue by Caro-Ca** [kdmurray91/kWIP#26]
Dear, 
I used bioconda to install kWIP. Additionally, I followed the steps on Example kWIP Analysis Protocols in which I could ran successfully the first two steps. Now I am facing a problem while running `Rscript img.R.` I copied the util/img.R script to the folder I am working on as it is said in: 

> We also need the img.R script which comes with kWIP, but isn’t installed. Hereafter I assume that you have this script in the analysis directory, ~/rice_kwip. Copy it with cp util/img.R ~/rice_kwip from the directory you git clone-d or unziped kWIP into.

This is the error message:
```
~/kWIP/strope: Rscript img.R strope
Error in library(fields, quietly = T) : 
  there is no package called ‘fields’
Execution halted
```

Thank you in advance for your help.

**Comment by Caro-Ca** [comment]
I could run img.R on Rstudio, but is there a way to do it in Linux? I know I need to install the library fields but I could not find anything similar to that on the website.

**Comment by kdm9** [comment]
sorry, I can't quite tell from your issue, but have you tried to install fields on the machine you're running img.R on? It seems to be missing. If you have not, try `R -e 'install.package(fields)'` first to install it.

**Comment by Caro-Ca** [comment]
Thank you for your help.
