### ISSUE TITLE
Distance units

### ISSUE THREAD

**Issue by andersgs** [kdmurray91/kWIP#4]
Hi Kevin.

Great tool. I am giving it a go at the moment. Had no issues getting it up and running. I am just looking at the distance matrix, and am wondering, what are the units?

Cheers.

Anders.

**Comment by kdmurray91** [comment]
Hi Anders,

Thanks! Glad it works for you. The units are entirely arbitrary and are relative to the diversity of your samples. Distances are normalised such that everything has a distance of 0 from itself.

Hope that helps,
Kevin

**Comment by kdmurray91** [comment]
It's been a week without further questions, so I'm going to close this issue. Thanks for using `kWIP`, and if you have any further questions don't hesitate to contact me.
