### ISSUE TITLE
Diagonal calculated twice

### ISSUE THREAD

**Issue by chengsoonong** [kdmurray91/kWIP#8]
In the calculation of the kernel matrix, the items along the diagonal are computed twice, i.e when i=j.

**Comment by kdmurray91** [comment]
Hi Cheng,

Thanks for the report. Just to clarify, do you mean in the pairwise comparison of each sample (as in [here](https://github.com/kdmurray91/kWIP/blob/master/src/kernel.cc#L142)) or elsewhere? I'm a little confused, as with the latest master I do not see the pairwise comparisons calculated twice for the digaonal.

```
 $ ./bin/kwip data/defined-1.ct data/defined-2.ct data/defined-3.ct data/defined-4.ct
kwip version 0.1.8-33-gb8fd9c9
Calculating entropy weighting vector:
  - Loading hashes into a population frequency vector:
    - Loaded 'data/defined-3.ct' (3)
    - Loaded 'data/defined-2.ct' (2)
    - Loaded 'data/defined-1.ct' (1)
    - Loaded 'data/defined-4.ct' (4)
 - Finished loading hashes!
 - Occupancy rate of population hash: 0.43299
1 x 1 done!
1 x 2 done!
1 x 3 done!
1 x 4 done!
2 x 2 done!
2 x 3 done!
2 x 4 done!
3 x 3 done!
3 x 4 done!
4 x 4 done!
Done all!
	defined-1	defined-2	defined-3	defined-4
defined-1	0	0.718671	0.892528	1.37207
defined-2	0.718671	0	1.34954	1.36146
defined-3	0.892528	1.34954	0	1.285
defined-4	1.37207	1.36146	1.285	0

```

**Comment by chengsoonong** [comment]
Sorry for the imprecise bug report. When i == j, (the diagonal), you can skip the second call to _get_hash. Depending on how your memory management works, you could just add an extra if statement there, or you could write another for loop to just compute the diagonal.

**Comment by kdmurray91** [comment]
Ah, I see what you mean. I believe that this isn't a concern performance wise, as `_get_hash` returns a shared pointer to a single instance of the hash (reading the hash in afresh if it is not in the cache). And with i=j, it's unlikely to have to read the hash in again, as the hash will be toward the start of the LRU cache due to being accessed as the `i`-th hash (i.e. being `ht1`, a few lines above).

**Comment by kdmurray91** [comment]
Are there other reasons that I haven't covered where the current behaviour is a bad idea? I can't think of any, but you may have had something in mind.

**Comment by chengsoonong** [comment]
I find that it is conceptually different to compute with two hashes or one hash. 

As long as the rest of your code does not violate the state, then things are ok. For example, if you do something like dividing each count by 10 before computing an inner product, when you have one hash, due to the fact that it is pointing to the same block of memory, you may inadvertently divide by 100 (10 twice). I did not look for such gotchas in your code, but you should have a think about it.

**Comment by kdmurray91** [comment]
Conceptually yes, but actually, as it's implemented now, I can't see any difference. As you say, it's basically a pointer to the same memory address. As you say, there are gotchas here, but I don't change the hash in any way; any manipulation (like you /10) happens on each element as part of the kernel calculation.

One thing that should probably happen is converting occurrences of `khmer::CountingHash` to `const khmer::CountingHash` to enforce that these being immutable objects.

**Comment by warthmann** [comment]
I am stating the obvious, but I am doing it anyway: To me this is a bug. And whether or not it currently has consequences should not play any role at all. We need to strive for bug free code as we have no idea what future developments bring and whether or not this glitch is then remembered or noticed.

Ceterum censeo:
I think kwip should write out the population hashes. I am currently trying to connect our approach to pop gen theory on dominant markers and without his hash (and the option to retrieve it for subsets of the data) I am operating in the dark.


On 23 Nov 2015, at 10:56 , Kevin Murray <notifications@github.com<mailto:notifications@github.com>> wrote:


Conceptually yes, but actually, as it's implemented now, I can't see any difference. As you say, it's basically a pointer to the same memory address. As you say, there are gotchas here, but I don't change the hash in any way; any manipulation (like you /10) happens on each element as part of the kernel calculation.

One thing that should probably happen is converting occurrences of khmer::CountingHash to const khmer::CountingHash to enforce that these being immutable objects.

**Comment by kdmurray91** [comment]
Norman, this a C++ optimisation to the algorithm. It's valid C++, and buggy code won't compile if I use the `const` keyword as I say we should above.
