### ISSUE TITLE
Check for positive semidefiniteness

### ISSUE THREAD

**Issue by chengsoonong** [kdmurray91/kWIP#9]
It is often the case the numerical difficulties result in a kernel matrix that is not positive semidefinite (and hence the distance matrix is not Euclidean). Therefore it would be nice to have a routine to check whether a particular kernel matrix is positive semidefinite, by computing an eigenvalue decomposition, and making sure that the eigenvalues are real (means the matrix is symmetric) and greater than or equal to zero. Eigenvalues that are a little bit negative (-1e-5) are ok, but anything more would be worrying.

It would be good to also provide an option to write out the normalised kernel matrix. It may be that the original kernel matrix is PSD but the normalised one is numerically not PSD.

If eigenvalues are a little bit negative, then one might wish to add a small diagonal to the normalised kernel matrix. Such a routine would be useful, so that the resulting distance matrix is really Euclidean, which might be expected by downstream analysis.

**Comment by kdmurray91** [comment]
Yup, all of these are great suggestions. They won't be that easy to implement, mainly because they will require moving to the Eigen C++ linear algebra library for storing and performing operations upon the kernel and distance matrices. In your opinion, are these features worthy of inclusion in the first version released with the paper (i.e. in the next month or two), or are they less crucial (i.e. can wait for January or thereabouts once the paper is in review)?

**Comment by kdmurray91** [comment]
To put a number to it, I recon that I could get all this done in 1 day of coding or less. It won't be that difficult, hopefully.

**Comment by kdmurray91** [comment]
Unless that is you reckon that it is OK to have this functionality as a separate python script, then it would be easy. I probably would prefer to have it as a part of kWIP itself, as then everyone has to get the readouts (much like calculating & displaying the collision rate of the population hash). But let me know your thoughts, I'm open to either solution.

**Comment by kdmurray91** [comment]
Well, I had a half hour free this arvo and had a quick go at using eigen to calculate such things. The hacking is at https://github.com/kdmurray91/kWIP/tree/eigencalc if anyone is interested. Looks as though it will be easier than I though.

**Comment by kdmurray91** [comment]
@chengsoonong This has now all be implemented. You should see a warning about non-PSD kernel matrices, or confirmation that the matrix is PSD.
